var annotated =
[
    [ "pmp", "namespacepmp.html", [
      [ "AllocationException", "classpmp_1_1_allocation_exception.html", null ],
      [ "BoundingBox", "classpmp_1_1_bounding_box.html", "classpmp_1_1_bounding_box" ],
      [ "Curvature", "classpmp_1_1_curvature.html", "classpmp_1_1_curvature" ],
      [ "Decimation", "classpmp_1_1_decimation.html", "classpmp_1_1_decimation" ],
      [ "Edge", "classpmp_1_1_edge.html", null ],
      [ "EdgeProperty", "classpmp_1_1_edge_property.html", "classpmp_1_1_edge_property" ],
      [ "Face", "classpmp_1_1_face.html", null ],
      [ "FaceProperty", "classpmp_1_1_face_property.html", "classpmp_1_1_face_property" ],
      [ "Fairing", "classpmp_1_1_fairing.html", "classpmp_1_1_fairing" ],
      [ "Features", "classpmp_1_1_features.html", "classpmp_1_1_features" ],
      [ "Geodesics", "classpmp_1_1_geodesics.html", "classpmp_1_1_geodesics" ],
      [ "Halfedge", "classpmp_1_1_halfedge.html", null ],
      [ "HalfedgeProperty", "classpmp_1_1_halfedge_property.html", "classpmp_1_1_halfedge_property" ],
      [ "Handle", "classpmp_1_1_handle.html", "classpmp_1_1_handle" ],
      [ "Heap", "classpmp_1_1_heap.html", "classpmp_1_1_heap" ],
      [ "HoleFilling", "classpmp_1_1_hole_filling.html", "classpmp_1_1_hole_filling" ],
      [ "InvalidInputException", "classpmp_1_1_invalid_input_exception.html", null ],
      [ "IOException", "classpmp_1_1_i_o_exception.html", null ],
      [ "IOFlags", "structpmp_1_1_i_o_flags.html", "structpmp_1_1_i_o_flags" ],
      [ "Matrix", "classpmp_1_1_matrix.html", "classpmp_1_1_matrix" ],
      [ "MemoryUsage", "classpmp_1_1_memory_usage.html", null ],
      [ "MeshViewer", "classpmp_1_1_mesh_viewer.html", "classpmp_1_1_mesh_viewer" ],
      [ "NormalCone", "classpmp_1_1_normal_cone.html", "classpmp_1_1_normal_cone" ],
      [ "Normals", "classpmp_1_1_normals.html", null ],
      [ "ObjectProperty", "classpmp_1_1_object_property.html", "classpmp_1_1_object_property" ],
      [ "Parameterization", "classpmp_1_1_parameterization.html", "classpmp_1_1_parameterization" ],
      [ "Quadric", "classpmp_1_1_quadric.html", "classpmp_1_1_quadric" ],
      [ "Remeshing", "classpmp_1_1_remeshing.html", "classpmp_1_1_remeshing" ],
      [ "Shader", "classpmp_1_1_shader.html", "classpmp_1_1_shader" ],
      [ "Shapes", "classpmp_1_1_shapes.html", null ],
      [ "Smoothing", "classpmp_1_1_smoothing.html", "classpmp_1_1_smoothing" ],
      [ "SolverException", "classpmp_1_1_solver_exception.html", null ],
      [ "Subdivision", "classpmp_1_1_subdivision.html", "classpmp_1_1_subdivision" ],
      [ "SurfaceMesh", "classpmp_1_1_surface_mesh.html", "classpmp_1_1_surface_mesh" ],
      [ "SurfaceMeshGL", "classpmp_1_1_surface_mesh_g_l.html", "classpmp_1_1_surface_mesh_g_l" ],
      [ "Timer", "classpmp_1_1_timer.html", "classpmp_1_1_timer" ],
      [ "TopologyException", "classpmp_1_1_topology_exception.html", null ],
      [ "TrackballViewer", "classpmp_1_1_trackball_viewer.html", "classpmp_1_1_trackball_viewer" ],
      [ "TriangleKdTree", "classpmp_1_1_triangle_kd_tree.html", "classpmp_1_1_triangle_kd_tree" ],
      [ "Triangulation", "classpmp_1_1_triangulation.html", "classpmp_1_1_triangulation" ],
      [ "Vertex", "classpmp_1_1_vertex.html", null ],
      [ "VertexCurvature", "structpmp_1_1_vertex_curvature.html", null ],
      [ "VertexProperty", "classpmp_1_1_vertex_property.html", "classpmp_1_1_vertex_property" ],
      [ "Window", "classpmp_1_1_window.html", "classpmp_1_1_window" ]
    ] ]
];